# Broadcasting 
### --> Permet de faire facilement des opération entre des tableaux via Numpy

# Import des packages

In [ ]:
import numpy as np

# Premiers Tests

In [18]:
np.random.seed(0)
A = np.random.randint(0,10,[2,3])
B = np.ones((3,1))

In [16]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [19]:
B

array([[1.],
       [1.],
       [1.]])

In [20]:
A + B # On ne peu faire ce genre d'opération qu'avec des tableaux qui ont les même dimensions (pas vraiment)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

# Exstension de certaines dimensions de mes tableaux (Broadcasting)

In [10]:
A + 2

array([[ 7,  2,  5],
       [ 5,  9, 11]])

### Quand on fait du Broadcasting, il y a des règles à suivre
##### - Chacune des dimensions dans A et dans B, doivent être égale de maniere respective
##### - Si on a des dimensions différentes alors la dimensions respective était égale à 1

### Exercice
##### résultat d'une somme entre une matrice (4,1) et une matrice (1,3)

In [22]:
A = np.random.randint(0,10,[4,1])
B = np.ones((1,3))
A + B # le Vecteur A et le Vecteur B vont mutuellement sétendre l'un sur l'autre pour couvrir une surface de (4,3)

array([[8., 8., 8.],
       [7., 7., 7.],
       [9., 9., 9.],
       [9., 9., 9.]])

### Attention /!\

In [24]:
A = np.random.randint(0,10,[4,1])
B = np.ones((3,))
A + B # On obtient le même exact résultat car lorsqu'on écris des dimensions incomplètes, 
      # le 3 ici est considéré comme la dernière dimension du tableau, (ici l'axe 1)

array([[ 9.,  9.,  9.],
       [ 2.,  2.,  2.],
       [ 6.,  6.,  6.],
       [10., 10., 10.]])

##### Toujours vérifier les dimensions de nos tableaux (utiliser la fonction .reshape() pour redimensionner nos tableaux lorsqu'il sont incomplets